### ISSUE TITLE
初始化报错

### ISSUE THREAD

**Issue by EricLiuCN** [Xavier-Lam/ys7#2]
我的环境是phpstudy8.1.1.2
php版本是7.3.4nts
框架是 thinkphp3.2

头部也已经引入了
use Neteast\YS7\YS7Auth;
use Neteast\YS7\YS7Client;

        Vendor('autoload');

        $appKey = "";
        $appSecret = "";
        $auth = new YS7Auth($appKey, $appSecret);
        $client = new YS7Client($auth);

Declaration of Neteast\YS7\Auth\BaseAuth::isInvalidAuthError(Shisa\HTTPClient\Exceptions\ResponseError $e) must be compatible with Shisa\HTTPClient\Auth\AbstractAuth::isInvalidAuthError($e)

请问大佬这是什么原因呢？能给点解决这个问题思路吗？

还有我看github上面的tag版本有0.2.1  但是packagist.org上最高到 0.2.0

**Comment by manhere** [comment]
php报错等级不同造成的，可以临时屏蔽E_STRICT警告

**Comment by Xavier-Lam** [comment]
我这边有更新过基础类库shisa\httpclient 要限制一下shisa\httpclient的最高版本 应该0.1.0版本是ok的
或者要把这个项目的继承声明改成和基类一致

**Comment by EricLiuCN** [comment]
好的 感谢分享
